# Compiler settings
CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++11 -g -Isrc
YACC = bison
YACCFLAGS = -d -v

LEX = flex
LEXFLAGS =

# Directories
SRC_DIR = src
BUILD_DIR = build
OUTPUT_DIR = outputs

# Target executable
TARGET = compiler

# Source files
YACC_SRC = $(SRC_DIR)/parser.y
LEX_SRC  = $(SRC_DIR)/lexer.l
CPP_SRC  = $(SRC_DIR)/ast.cpp $(SRC_DIR)/symbol.cpp $(SRC_DIR)/semantic.cpp

# Generated files
YACC_C = $(BUILD_DIR)/parser.tab.c
YACC_H = $(BUILD_DIR)/parser.tab.h
LEX_C  = $(BUILD_DIR)/lex.yy.c

# Object files
OBJS = $(YACC_C:.c=.o) $(LEX_C:.c=.o) $(CPP_SRC:$(SRC_DIR)/%.cpp=$(BUILD_DIR)/%.o)

# Default target
all: $(TARGET)

# Build the compiler
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^


# Generate parser from yacc file
$(YACC_C) $(YACC_H): $(YACC_SRC)
	mkdir -p $(BUILD_DIR)
	$(YACC) $(YACCFLAGS) --defines=$(YACC_H) -o $(YACC_C) $<
	

# Generate lexer from lex file
$(LEX_C): $(LEX_SRC) $(YACC_H)
	$(LEX) $(LEXFLAGS) -o $(LEX_C) $<

# Compile C files generated by yacc/lex
$(BUILD_DIR)/%.o: $(BUILD_DIR)/%.c
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Compile C++ source files  <-- ADD THIS
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp
	mkdir -p $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Clean build artifacts
clean:
	rm -f $(TARGET) $(OBJS) parser.c parser.h lexer.c parser.output

.PHONY: all clean
